# Generated by Django 3.0.8 on 2020-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
