# Generated by Django 3.1.4 on 2021-05-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201210_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='Materials',
        ),
        migrations.AddField(
            model_name='material',
            name='classroom',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='classroom.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='Content',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
